version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    volumes:
      - .docker/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: applifting
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    networks:
      - backend

  rest-server:
    image: rest-server:latest
    container_name: resr-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend: